# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wordcloud.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wordcloud.proto',
  package='wordcloud',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fwordcloud.proto\x12\twordcloud\"+\n\x16\x43reateWordCloudRequest\x12\x11\n\thatena_id\x18\x01 \x01(\t\")\n\x14\x43reateWordCloudReply\x12\x11\n\twordcloud\x18\x01 \x01(\x0c\x32\x64\n\tWordcloud\x12W\n\x0f\x43reateWordCloud\x12!.wordcloud.CreateWordCloudRequest\x1a\x1f.wordcloud.CreateWordCloudReply\"\x00\x62\x06proto3'
)




_CREATEWORDCLOUDREQUEST = _descriptor.Descriptor(
  name='CreateWordCloudRequest',
  full_name='wordcloud.CreateWordCloudRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hatena_id', full_name='wordcloud.CreateWordCloudRequest.hatena_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=73,
)


_CREATEWORDCLOUDREPLY = _descriptor.Descriptor(
  name='CreateWordCloudReply',
  full_name='wordcloud.CreateWordCloudReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wordcloud', full_name='wordcloud.CreateWordCloudReply.wordcloud', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['CreateWordCloudRequest'] = _CREATEWORDCLOUDREQUEST
DESCRIPTOR.message_types_by_name['CreateWordCloudReply'] = _CREATEWORDCLOUDREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateWordCloudRequest = _reflection.GeneratedProtocolMessageType('CreateWordCloudRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEWORDCLOUDREQUEST,
  '__module__' : 'wordcloud_pb2'
  # @@protoc_insertion_point(class_scope:wordcloud.CreateWordCloudRequest)
  })
_sym_db.RegisterMessage(CreateWordCloudRequest)

CreateWordCloudReply = _reflection.GeneratedProtocolMessageType('CreateWordCloudReply', (_message.Message,), {
  'DESCRIPTOR' : _CREATEWORDCLOUDREPLY,
  '__module__' : 'wordcloud_pb2'
  # @@protoc_insertion_point(class_scope:wordcloud.CreateWordCloudReply)
  })
_sym_db.RegisterMessage(CreateWordCloudReply)



_WORDCLOUD = _descriptor.ServiceDescriptor(
  name='Wordcloud',
  full_name='wordcloud.Wordcloud',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=118,
  serialized_end=218,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateWordCloud',
    full_name='wordcloud.Wordcloud.CreateWordCloud',
    index=0,
    containing_service=None,
    input_type=_CREATEWORDCLOUDREQUEST,
    output_type=_CREATEWORDCLOUDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORDCLOUD)

DESCRIPTOR.services_by_name['Wordcloud'] = _WORDCLOUD

# @@protoc_insertion_point(module_scope)
