# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import wordcloud_pb2 as wordcloud__pb2


class WordcloudStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateWordCloud = channel.unary_unary(
                '/wordcloud.Wordcloud/CreateWordCloud',
                request_serializer=wordcloud__pb2.CreateWordCloudRequest.SerializeToString,
                response_deserializer=wordcloud__pb2.CreateWordCloudReply.FromString,
                )


class WordcloudServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateWordCloud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WordcloudServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateWordCloud': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWordCloud,
                    request_deserializer=wordcloud__pb2.CreateWordCloudRequest.FromString,
                    response_serializer=wordcloud__pb2.CreateWordCloudReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wordcloud.Wordcloud', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Wordcloud(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateWordCloud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wordcloud.Wordcloud/CreateWordCloud',
            wordcloud__pb2.CreateWordCloudRequest.SerializeToString,
            wordcloud__pb2.CreateWordCloudReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
