# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import learner_pb2 as learner__pb2


class LearnerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Learn = channel.unary_unary(
                '/learner.Learner/Learn',
                request_serializer=learner__pb2.LearnRequest.SerializeToString,
                response_deserializer=learner__pb2.LearnReply.FromString,
                )
        self.GetSuggestion = channel.unary_unary(
                '/learner.Learner/GetSuggestion',
                request_serializer=learner__pb2.GetSuggestionRequest.SerializeToString,
                response_deserializer=learner__pb2.GetSuggestionReply.FromString,
                )
        self.GetHotentrySuggestion = channel.unary_unary(
                '/learner.Learner/GetHotentrySuggestion',
                request_serializer=learner__pb2.GetHotentrySuggestionRequest.SerializeToString,
                response_deserializer=learner__pb2.GetSuggestionReply.FromString,
                )
        self.ExistsHatenaID = channel.unary_unary(
                '/learner.Learner/ExistsHatenaID',
                request_serializer=learner__pb2.ExistsHatenaIDRequest.SerializeToString,
                response_deserializer=learner__pb2.ExistsHatenaIDReply.FromString,
                )


class LearnerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Learn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSuggestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHotentrySuggestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExistsHatenaID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LearnerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Learn': grpc.unary_unary_rpc_method_handler(
                    servicer.Learn,
                    request_deserializer=learner__pb2.LearnRequest.FromString,
                    response_serializer=learner__pb2.LearnReply.SerializeToString,
            ),
            'GetSuggestion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSuggestion,
                    request_deserializer=learner__pb2.GetSuggestionRequest.FromString,
                    response_serializer=learner__pb2.GetSuggestionReply.SerializeToString,
            ),
            'GetHotentrySuggestion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHotentrySuggestion,
                    request_deserializer=learner__pb2.GetHotentrySuggestionRequest.FromString,
                    response_serializer=learner__pb2.GetSuggestionReply.SerializeToString,
            ),
            'ExistsHatenaID': grpc.unary_unary_rpc_method_handler(
                    servicer.ExistsHatenaID,
                    request_deserializer=learner__pb2.ExistsHatenaIDRequest.FromString,
                    response_serializer=learner__pb2.ExistsHatenaIDReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'learner.Learner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Learner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Learn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learner.Learner/Learn',
            learner__pb2.LearnRequest.SerializeToString,
            learner__pb2.LearnReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSuggestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learner.Learner/GetSuggestion',
            learner__pb2.GetSuggestionRequest.SerializeToString,
            learner__pb2.GetSuggestionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHotentrySuggestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learner.Learner/GetHotentrySuggestion',
            learner__pb2.GetHotentrySuggestionRequest.SerializeToString,
            learner__pb2.GetSuggestionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExistsHatenaID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learner.Learner/ExistsHatenaID',
            learner__pb2.ExistsHatenaIDRequest.SerializeToString,
            learner__pb2.ExistsHatenaIDReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
